# The release will be uploaded to PyPI

name: Language Server CD

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Package and Upload
        env:
          GALAXYLS_VERSION: ${{ steps.get_version.outputs.version-without-v }}
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*

      - name: Archive packages
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
